### ISSUE TITLE
Link to "bin" points to parent on MacOS

### ISSUE THREAD

**Issue by posidron** [MozillaSecurity/fuzzfetch#1]
lrwxr-xr-x  1 posidron  staff    2 Jun  1 23:03 bin -> ..

Nightly.app/Contents/MacOS contains the stuff but 'bin' in 'dist' is linked to the parent.

**Comment by pyoor** [comment]
Apparently each of the build types (linux, osx, win) all have a different directory structure inside the archive.  Rather than trying to support each one, I vote to remove it entirely.

We originally did this to support DOMFuzz as it needed the binary to reside in build/dist/bin.  I'll look into seeing how difficult it'd be to remove that in favor of specifying the bin path explicitly.

**Comment by jschwartzentruber** [comment]
Discussed with @pyoor and we'll keep it for now. This may simplify things for the user and provides continuity with local builds.
